logging:
#  file: monasca-transformData.log
  level: INFO

consumerTopic: custom-metrics
producerTopic: metrics
poolFactor: 100

kafka:
  bootstrap.servers: localhost:9092
  group.id: monasca-transformData
  max.threads: 1
  go.batch.producer: false
  queue.buffering.max.messages: 100000
  message.timeout.ms: 5000
  consumer.auto.commit: true

tenantId: 1231243
version: v1.0.9